import { createContext, useContext, useEffect, useState } from "react";
import { exchangeRates } from "@/lib/currency";

export type Language = "id" | "en" | "es" | "fr" | "de";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    formatCurrency: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    id: {
        "settings.title": "Pengaturan",
        "settings.subtitle": "Kelola preferensi Anda",
        "settings.account": "Akun Saya",
        "settings.appearance": "Tampilan",
        "settings.preferences": "Preferensi",
        "settings.about": "Tentang",
        "settings.logout": "Keluar dari Akun",
        "settings.logoutSuccess": "Berhasil keluar",
        "settings.logoutError": "Gagal keluar",
        "settings.darkMode": "Mode Gelap",
        "settings.darkModeActive": "Tema gelap aktif",
        "settings.lightModeActive": "Tema terang aktif",
        "settings.themeColor": "Warna Tema",
        "settings.language": "Bahasa",
        "settings.notifications": "Notifikasi",
        "settings.currency": "Mata Uang",
        "settings.privacyPolicy": "Kebijakan Privasi",
        "settings.aboutApp": "Tentang Fiscal",
        "common.soon": "Segera",
        "nav.chat": "AI Chat",
        "nav.settings": "Pengaturan",
        "dashboard.welcome": "Halo! 👋",
        "dashboard.welcomeSubtitle": "siap membantu",
        "dashboard.intro": "Ketik transaksi seperti \"Beli kopi 25rb\" atau upload struk dengan tombol klip. Saya juga bisa menjawab pertanyaan keuanganmu!",
        "dashboard.suggestion.expense": "💸 Beli makan siang 20rb",
        "dashboard.suggestion.income": "💰 Gaji bulan ini 5jt",
        "dashboard.suggestion.analytics": "📊 Pengeluaran minggu ini?",
        "dashboard.suggestion.tips": "💡 Tips menghemat uang",
        "balance.total": "Total Saldo",
        "balance.income": "Pemasukan",
        "balance.expense": "Pengeluaran",
        "balance.auto": "Otomatis",
        "common.processing": "Sedang memproses...",
        "common.cancel": "Batal",
        "common.save": "Simpan",
        "common.delete": "Hapus",
        "common.edit": "Edit",
        "common.today": "Hari ini",
        "wallet.title": "Dompet",
        "wallet.export": "Ekspor",
        "wallet.exportCsv": "Ekspor CSV",
        "wallet.exportPdf": "Ekspor PDF",
        "wallet.trend": "Tren 6 Bulan Terakhir",
        "wallet.categoryBreakdown": "Pengeluaran per Kategori",
        "wallet.insight": "Insight Bulan Ini",
        "wallet.recentTransactions": "Transaksi Terakhir",
        "wallet.noTransactions": "Belum ada transaksi",
        "reports.title": "Laporan",
        "reports.monthly": "Laporan Bulanan",
        "reports.balanceMonth": "Saldo Bulan Ini",
        "reports.trend": "Tren 6 Bulan",
        "reports.topExpenses": "Top Pengeluaran",
        "insights.title": "Wawasan",
        "insights.financial": "Wawasan Keuangan",
        "insights.savingsRate": "Rasio Tabungan",
        "insights.avgDaily": "Rata-rata/Hari",
        "insights.trend14": "Tren Pengeluaran 14 Hari",
        "insights.breakdown": "Rincian Kategori",
        "insights.tips": "Tips Pintar",
        "goals.title": "Budget Goals",
        "goals.totalBudget": "Total Budget Bulan Ini",
        "goals.overBudget": "⚠️ Budget sudah terlampaui!",
        "goals.remaining": "tersisa",
        "goals.loading": "Memuat...",
        "goals.empty": "Belum ada budget goal",
        "goals.emptyDesc": "Buat budget untuk mengontrol pengeluaran",
        "goals.status.over": "Over budget!",
        "goals.status.near": "Hampir limit",
        "goals.status.onTrack": "On track",
        "goals.add": "Tambah Budget Goal",
        "goals.selectCategory": "Pilih kategori",
        "goals.amountPlaceholder": "Nominal budget",
        "transaction.add": "Tambah Transaksi",
        "transaction.manual": "Manual",
        "transaction.receipt": "Upload Struk",
        "transaction.receiptPrompt": "Tap untuk upload foto struk",
        "transaction.aiProcessing": "AI Memproses...",
        "transaction.amount": "Jumlah",
        "transaction.category": "Kategori",
        "transaction.date": "Tanggal",
        "transaction.note": "Catatan (opsional)",
        "transaction.notePlaceholder": "Tambahkan catatan...",
        "transaction.save": "Simpan Transaksi",
        "transaction.saved": "Transaksi tersimpan",
        "transaction.cancelled": "Dibatalkan",
        "transaction.confirm": "Konfirmasi",
        "alerts.budgetOver": "Budget Terlampaui!",
        "alerts.budgetOverDesc": "Pengeluaran {category} sudah melebihi budget",
        "alerts.budgetNear": "Hampir Limit",
        "alerts.budgetNearDesc": "{category} sudah {percent}% dari budget",
        "alerts.spendingFast": "Spending Cepat",
        "alerts.spendingFastDesc": "Kamu menghabiskan lebih cepat dari rata-rata",
        "alerts.expenseIncomeHigh": "Pengeluaran Melebihi Pemasukan!",
        "alerts.ratioHigh": "Ratio Tinggi",
        "alerts.expenseHighDesc": "Pengeluaran bulan ini lebih besar dari pemasukan!",
        "alerts.ratioHighDesc": "Kamu sudah menghabiskan {percent}% dari pemasukan",
        "recurring.title": "Transaksi Berulang",
        "recurring.add": "Tambah Transaksi Berulang",
        "recurring.type": "Tipe",
        "recurring.type.income": "Pemasukan",
        "recurring.type.expense": "Pengeluaran",
        "recurring.amount": "Jumlah",
        "recurring.category": "Kategori",
        "recurring.description": "Deskripsi (opsional)",
        "recurring.frequency": "Frekuensi",
        "recurring.frequency.daily": "Harian",
        "recurring.frequency.weekly": "Mingguan",
        "recurring.frequency.monthly": "Bulanan",
        "recurring.frequency.yearly": "Tahunan",
        "recurring.startDate": "Tanggal Mulai",
        "recurring.next": "Selanjutnya: {date}",
        "recurring.empty": "Belum ada transaksi berulang",
        "recurring.emptyDesc": "Tambahkan tagihan bulanan atau gaji rutin",
        "recurring.active": "Diaktifkan",
        "recurring.inactive": "Dinonaktifkan",
        "recurring.saved": "Transaksi berulang tersimpan",
        "recurring.deleted": "Transaksi berulang dihapus",
        "privacy.intro": "Privasi Anda penting bagi kami. Kebijakan ini menjelaskan bagaimana Fiscal mengumpulkan, menggunakan, dan melindungi data Anda.",
        "privacy.dataCollection": "Pengumpulan Data",
        "privacy.dataCollectionDesc": "Kami mengumpulkan data yang Anda berikan secara langsung, seperti detail transaksi. Kami tidak menjual data pribadi Anda.",
        "privacy.security": "Keamanan",
        "privacy.securityDesc": "Kami menggunakan enkripsi standar untuk melindungi informasi keuangan Anda.",
        "privacy.contact": "Kontak",
        "privacy.contactDesc": "Jika Anda memiliki pertanyaan, hubungi kami di MAN Insan Cendekia Siak.",
    },
    en: {
        "settings.title": "Settings",
        "settings.subtitle": "Manage your preferences",
        "settings.account": "My Account",
        "settings.appearance": "Appearance",
        "settings.preferences": "Preferences",
        "settings.about": "About",
        "settings.logout": "Log Out",
        "settings.logoutSuccess": "Logged out successfully",
        "settings.logoutError": "Failed to log out",
        "settings.darkMode": "Dark Mode",
        "settings.darkModeActive": "Dark mode active",
        "settings.lightModeActive": "Light mode active",
        "settings.themeColor": "Theme Color",
        "settings.language": "Language",
        "settings.notifications": "Notifications",
        "settings.currency": "Currency",
        "settings.privacyPolicy": "Privacy Policy",
        "settings.aboutApp": "About Fiscal",
        "common.soon": "Soon",
        "nav.chat": "AI Chat",
        "nav.settings": "Settings",
        "dashboard.welcome": "Hello! 👋",
        "dashboard.welcomeSubtitle": "ready to help",
        "dashboard.intro": "Type transactions like \"Buy coffee $5\" or upload a receipt. I can also answer your financial questions!",
        "dashboard.suggestion.expense": "💸 Buy lunch $15",
        "dashboard.suggestion.income": "💰 Monthly salary $3000",
        "dashboard.suggestion.analytics": "📊 Weekly spending?",
        "dashboard.suggestion.tips": "💡 Money saving tips",
        "balance.total": "Total Balance",
        "balance.income": "Income",
        "balance.expense": "Expense",
        "balance.auto": "Auto",
        "common.processing": "Processing...",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.today": "Today",
        "wallet.title": "Wallet",
        "wallet.export": "Export",
        "wallet.exportCsv": "Export CSV",
        "wallet.exportPdf": "Export PDF",
        "wallet.trend": "Last 6 Months Trend",
        "wallet.categoryBreakdown": "Expenses by Category",
        "wallet.insight": "Monthly Insight",
        "wallet.recentTransactions": "Recent Transactions",
        "wallet.noTransactions": "No transactions yet",
        "reports.title": "Reports",
        "reports.monthly": "Monthly Report",
        "reports.balanceMonth": "Monthly Balance",
        "reports.trend": "6 Month Trend",
        "reports.topExpenses": "Top Expenses",
        "insights.title": "Insights",
        "insights.financial": "Financial Insights",
        "insights.savingsRate": "Savings Rate",
        "insights.avgDaily": "Avg/Day",
        "insights.trend14": "14 Day Spending Trend",
        "insights.breakdown": "Category Breakdown",
        "insights.tips": "Smart Tips",
        "goals.title": "Budget Goals",
        "goals.totalBudget": "Total Monthly Budget",
        "goals.overBudget": "⚠️ Budget exceeded!",
        "goals.remaining": "left",
        "goals.loading": "Loading...",
        "goals.empty": "No budget goals yet",
        "goals.emptyDesc": "Create a budget to control expenses",
        "goals.status.over": "Over budget!",
        "goals.status.near": "Near limit",
        "goals.status.onTrack": "On track",
        "goals.add": "Add Budget Goal",
        "goals.selectCategory": "Select category",
        "goals.amountPlaceholder": "Budget amount",
        "transaction.add": "Add Transaction",
        "transaction.manual": "Manual",
        "transaction.receipt": "Upload Receipt",
        "transaction.receiptPrompt": "Tap to upload receipt photo",
        "transaction.aiProcessing": "AI Processing...",
        "transaction.amount": "Amount",
        "transaction.category": "Category",
        "transaction.date": "Date",
        "transaction.note": "Note (optional)",
        "transaction.notePlaceholder": "Add a note...",
        "transaction.save": "Save Transaction",
        "transaction.saved": "Transaction saved",
        "transaction.cancelled": "Cancelled",
        "transaction.confirm": "Confirm",
        "alerts.budgetOver": "Budget Exceeded!",
        "alerts.budgetOverDesc": "{category} expenses exceeded budget",
        "alerts.budgetNear": "Near Limit",
        "alerts.budgetNearDesc": "{category} is at {percent}% of budget",
        "alerts.spendingFast": "Fast Spending",
        "alerts.spendingFastDesc": "You are spending faster than average",
        "alerts.expenseIncomeHigh": "Expenses Exceed Income!",
        "alerts.ratioHigh": "High Ratio",
        "alerts.expenseHighDesc": "This month's expenses exceed income!",
        "alerts.ratioHighDesc": "You have spent {percent}% of income",
        "recurring.title": "Recurring Transactions",
        "recurring.add": "Add Recurring Transaction",
        "recurring.type": "Type",
        "recurring.type.income": "Income",
        "recurring.type.expense": "Expense",
        "recurring.amount": "Amount",
        "recurring.category": "Category",
        "recurring.description": "Description (optional)",
        "recurring.frequency": "Frequency",
        "recurring.frequency.daily": "Daily",
        "recurring.frequency.weekly": "Weekly",
        "recurring.frequency.monthly": "Monthly",
        "recurring.frequency.yearly": "Yearly",
        "recurring.startDate": "Start Date",
        "recurring.next": "Next: {date}",
        "recurring.empty": "No recurring transactions",
        "recurring.emptyDesc": "Add monthly bills or salary",
        "recurring.active": "Activated",
        "recurring.inactive": "Deactivated",
        "recurring.saved": "Recurring transaction saved",
        "recurring.deleted": "Recurring transaction deleted",
        "privacy.intro": "Your privacy is important to us. This policy explains how Fiscal collects and protects your data.",
        "privacy.dataCollection": "Data Collection",
        "privacy.dataCollectionDesc": "We collect data you provide directly, such as transaction details. We do not sell your personal data.",
        "privacy.security": "Security",
        "privacy.securityDesc": "We use standard encryption to protect your financial information.",
        "privacy.contact": "Contact",
        "privacy.contactDesc": "If you have questions, contact us at MAN Insan Cendekia Siak.",
    },
    es: {
        "settings.title": "Configuración",
        "settings.subtitle": "Administra tus preferencias",
        "settings.account": "Mi Cuenta",
        "settings.appearance": "Apariencia",
        "settings.preferences": "Preferencias",
        "settings.about": "Acerca de",
        "settings.logout": "Cerrar Sesión",
        "settings.logoutSuccess": "Sesión cerrada con éxito",
        "settings.logoutError": "Error al cerrar sesión",
        "settings.darkMode": "Modo Oscuro",
        "settings.darkModeActive": "Modo oscuro activo",
        "settings.lightModeActive": "Modo claro activo",
        "settings.themeColor": "Color del Tema",
        "settings.language": "Idioma",
        "settings.notifications": "Notificaciones",
        "settings.currency": "Moneda",
        "settings.privacyPolicy": "Política de Privacidad",
        "settings.aboutApp": "Acerca de Fiscal",
        "common.soon": "Pronto",
        "nav.chat": "Chat IA",
        "nav.settings": "Ajustes",
        "dashboard.welcome": "¡Hola! 👋",
        "dashboard.welcomeSubtitle": "listo para ayudar",
        "dashboard.intro": "Escribe transacciones como \"Comprar café $5\" o sube un recibo. ¡También puedo responder tus preguntas financieras!",
        "dashboard.suggestion.expense": "💸 Comprar almuerzo $15",
        "dashboard.suggestion.income": "💰 Salario mensual $2000",
        "dashboard.suggestion.analytics": "📊 ¿Gasto semanal?",
        "dashboard.suggestion.tips": "💡 Consejos de ahorro",
        "balance.total": "Saldo Total",
        "balance.income": "Ingresos",
        "balance.expense": "Gastos",
        "balance.auto": "Auto",
        "common.processing": "Procesando...",
        "common.cancel": "Cancelar",
        "common.save": "Guardar",
        "common.delete": "Eliminar",
        "common.edit": "Editar",
        "common.today": "Hoy",
        "wallet.title": "Billetera",
        "wallet.export": "Exportar",
        "wallet.exportCsv": "Exportar CSV",
        "wallet.exportPdf": "Exportar PDF",
        "wallet.trend": "Tendencia últimos 6 meses",
        "wallet.categoryBreakdown": "Gastos por Categoría",
        "wallet.insight": "Insight Mensual",
        "wallet.recentTransactions": "Transacciones Recientes",
        "wallet.noTransactions": "Aún no hay transacciones",
        "reports.title": "Informes",
        "reports.monthly": "Informe Mensual",
        "reports.balanceMonth": "Saldo Mensual",
        "reports.trend": "Tendencia 6 Meses",
        "reports.topExpenses": "Gastos Principales",
        "insights.title": "Insights",
        "insights.financial": "Insights Financieros",
        "insights.savingsRate": "Tasa de Ahorro",
        "insights.avgDaily": "Prom/Día",
        "insights.trend14": "Tendencia Gastos 14 Días",
        "insights.breakdown": "Desglose por Categoría",
        "insights.tips": "Consejos Inteligentes",
        "goals.title": "Metas de Presupuesto",
        "goals.totalBudget": "Presupuesto Mensual Total",
        "goals.overBudget": "⚠️ ¡Presupuesto excedido!",
        "goals.remaining": "restante",
        "goals.loading": "Cargando...",
        "goals.empty": "Sin metas de presupuesto",
        "goals.emptyDesc": "Crea un presupuesto para controlar gastos",
        "goals.status.over": "¡Sobre presupuesto!",
        "goals.status.near": "Cerca del límite",
        "goals.status.onTrack": "En camino",
        "goals.add": "Añadir Meta",
        "goals.selectCategory": "Seleccionar categoría",
        "goals.amountPlaceholder": "Monto del presupuesto",
        "transaction.add": "Añadir Transacción",
        "transaction.manual": "Manual",
        "transaction.receipt": "Subir Recibo",
        "transaction.receiptPrompt": "Toque para subir foto",
        "transaction.aiProcessing": "IA Procesando...",
        "transaction.amount": "Monto",
        "transaction.category": "Categoría",
        "transaction.date": "Fecha",
        "transaction.note": "Nota (opcional)",
        "transaction.notePlaceholder": "Añadir nota...",
        "transaction.save": "Guardar Transacción",
        "transaction.saved": "Transacción guardada",
        "transaction.cancelled": "Cancelado",
        "transaction.confirm": "Confirmar",
        "alerts.budgetOver": "¡Presupuesto Excedido!",
        "alerts.budgetOverDesc": "Gastos de {category} excedieron presupuesto",
        "alerts.budgetNear": "Cerca del Límite",
        "alerts.budgetNearDesc": "{category} está al {percent}% del presupuesto",
        "alerts.spendingFast": "Gasto Rápido",
        "alerts.spendingFastDesc": "Estás gastando más rápido que el promedio",
        "alerts.expenseIncomeHigh": "¡Gastos Exceden Ingresos!",
        "alerts.ratioHigh": "Ratio Alto",
        "alerts.expenseHighDesc": "¡Gastos de este mes exceden ingresos!",
        "alerts.ratioHighDesc": "Has gastado {percent}% de los ingresos",
        "recurring.title": "Transacciones Recurrentes",
        "recurring.add": "Añadir Recurrente",
        "recurring.type": "Tipo",
        "recurring.type.income": "Ingreso",
        "recurring.type.expense": "Gasto",
        "recurring.amount": "Monto",
        "recurring.category": "Categoría",
        "recurring.description": "Descripción (opcional)",
        "recurring.frequency": "Frecuencia",
        "recurring.frequency.daily": "Diario",
        "recurring.frequency.weekly": "Semanal",
        "recurring.frequency.monthly": "Mensual",
        "recurring.frequency.yearly": "Anual",
        "recurring.startDate": "Fecha de Inicio",
        "recurring.next": "Próximo: {date}",
        "recurring.empty": "Sin transacciones recurrentes",
        "recurring.emptyDesc": "Añadir facturas o salario mensual",
        "recurring.active": "Activado",
        "recurring.inactive": "Desactivado",
        "recurring.saved": "Transacción recurrente guardada",
        "recurring.deleted": "Transacción recurrente eliminada",
        "privacy.intro": "Su privacidad es importante. Esta política explica cómo Fiscal recopila y protege sus datos.",
        "privacy.dataCollection": "Recopilación de Datos",
        "privacy.dataCollectionDesc": "Recopilamos datos que usted proporciona, como detalles de transacciones. No vendemos sus datos personales.",
        "privacy.security": "Seguridad",
        "privacy.securityDesc": "Utilizamos encriptación estándar para proteger su información financiera.",
        "privacy.contact": "Contacto",
        "privacy.contactDesc": "Si tiene preguntas, contáctenos en MAN Insan Cendekia Siak.",
    },
    fr: {
        "settings.title": "Paramètres",
        "settings.subtitle": "Gérer vos préférences",
        "settings.account": "Mon Compte",
        "settings.appearance": "Apparence",
        "settings.preferences": "Préférences",
        "settings.about": "À propos",
        "settings.logout": "Se Déconnecter",
        "settings.logoutSuccess": "Déconnexion réussie",
        "settings.logoutError": "Échec de la déconnexion",
        "settings.darkMode": "Mode Sombre",
        "settings.darkModeActive": "Mode sombre actif",
        "settings.lightModeActive": "Mode clair actif",
        "settings.themeColor": "Couleur du Thème",
        "settings.language": "Langue",
        "settings.notifications": "Notifications",
        "settings.currency": "Devise",
        "settings.privacyPolicy": "Politique de Confidentialité",
        "settings.aboutApp": "À propos de Fiscal",
        "common.soon": "Bientôt",
        "nav.chat": "Chat IA",
        "nav.settings": "Paramètres",
        "dashboard.welcome": "Bonjour! 👋",
        "dashboard.welcomeSubtitle": "prêt à aider",
        "dashboard.intro": "Tapez des transactions comme \"Café 5€\" ou téléchargez un reçu. Je peux aussi répondre à vos questions financières!",
        "dashboard.suggestion.expense": "💸 Déjeuner 15€",
        "dashboard.suggestion.income": "💰 Salaire mensuel 2500€",
        "dashboard.suggestion.analytics": "📊 Dépenses hebdo?",
        "dashboard.suggestion.tips": "💡 Conseils d'économie",
        "balance.total": "Solde Total",
        "balance.income": "Revenus",
        "balance.expense": "Dépenses",
        "balance.auto": "Auto",
        "common.processing": "Traitement...",
        "common.cancel": "Annuler",
        "common.save": "Enregistrer",
        "common.delete": "Supprimer",
        "common.edit": "Modifier",
        "common.today": "Aujourd'hui",
        "wallet.title": "Portefeuille",
        "wallet.export": "Exporter",
        "wallet.exportCsv": "Exporter CSV",
        "wallet.exportPdf": "Exporter PDF",
        "wallet.trend": "Tendance des 6 derniers mois",
        "wallet.categoryBreakdown": "Dépenses par Catégorie",
        "wallet.insight": "Aperçu Mensuel",
        "wallet.recentTransactions": "Transactions Récentes",
        "wallet.noTransactions": "Aucune transaction",
        "reports.title": "Rapports",
        "reports.monthly": "Rapport Mensuel",
        "reports.balanceMonth": "Solde Mensuel",
        "reports.trend": "Tendance 6 Mois",
        "reports.topExpenses": "Top Dépenses",
        "insights.title": "Aperçus",
        "insights.financial": "Aperçus Financiers",
        "insights.savingsRate": "Taux d'Épargne",
        "insights.avgDaily": "Moy/Jour",
        "insights.trend14": "Tendance Dépenses 14 Jours",
        "insights.breakdown": "Répartition par Catégorie",
        "insights.tips": "Conseils Intelligents",
        "goals.title": "Objectifs Budgétaires",
        "goals.totalBudget": "Budget Mensuel Total",
        "goals.overBudget": "⚠️ Budget dépassé !",
        "goals.remaining": "restant",
        "goals.loading": "Chargement...",
        "goals.empty": "Pas encore d'objectifs",
        "goals.emptyDesc": "Créez un budget pour contrôler les dépenses",
        "goals.status.over": "Budget dépassé !",
        "goals.status.near": "Proche de la limite",
        "goals.status.onTrack": "En bonne voie",
        "goals.add": "Ajouter un Objectif",
        "goals.selectCategory": "Choisir catégorie",
        "goals.amountPlaceholder": "Montant du budget",
        "transaction.add": "Ajouter Transaction",
        "transaction.manual": "Manuel",
        "transaction.receipt": "Télécharger Reçu",
        "transaction.receiptPrompt": "Appuyez pour photo",
        "transaction.aiProcessing": "IA en cours...",
        "transaction.amount": "Montant",
        "transaction.category": "Catégorie",
        "transaction.date": "Date",
        "transaction.note": "Note (optionnel)",
        "transaction.notePlaceholder": "Ajouter une note...",
        "transaction.save": "Enregistrer Transaction",
        "transaction.saved": "Transaction enregistrée",
        "transaction.cancelled": "Annulé",
        "transaction.confirm": "Confirmer",
        "alerts.budgetOver": "Budget Dépassé !",
        "alerts.budgetOverDesc": "Dépenses {category} dépassent le budget",
        "alerts.budgetNear": "Proche de la Limite",
        "alerts.budgetNearDesc": "{category} est à {percent}% du budget",
        "alerts.spendingFast": "Dépenses Rapides",
        "alerts.spendingFastDesc": "Vous dépensez plus vite que la moyenne",
        "alerts.expenseIncomeHigh": "Dépenses > Revenus !",
        "alerts.ratioHigh": "Ratio Élevé",
        "alerts.expenseHighDesc": "Les dépenses du mois dépassent les revenus !",
        "alerts.ratioHighDesc": "Vous avez dépensé {percent}% des revenus",
        "recurring.title": "Transactions Récurrentes",
        "recurring.add": "Ajouter Récurrence",
        "recurring.type": "Type",
        "recurring.type.income": "Revenu",
        "recurring.type.expense": "Dépense",
        "recurring.amount": "Montant",
        "recurring.category": "Catégorie",
        "recurring.description": "Description (optionnel)",
        "recurring.frequency": "Fréquence",
        "recurring.frequency.daily": "Quotidien",
        "recurring.frequency.weekly": "Hebdomadaire",
        "recurring.frequency.monthly": "Mensuel",
        "recurring.frequency.yearly": "Annuel",
        "recurring.startDate": "Date de Début",
        "recurring.next": "Suivant: {date}",
        "recurring.empty": "Aucune transaction récurrente",
        "recurring.emptyDesc": "Ajouter factures ou salaires",
        "recurring.active": "Activé",
        "recurring.inactive": "Désactivé",
        "recurring.saved": "Transaction récurrente enregistrée",
        "recurring.deleted": "Transaction récurrente supprimée",
        "privacy.intro": "Votre vie privée est importante. Cette politique explique comment Fiscal collecte et protège vos données.",
        "privacy.dataCollection": "Collecte de Données",
        "privacy.dataCollectionDesc": "Nous collectons les données que vous fournissez directement. Nous ne vendons pas vos données personnelles.",
        "privacy.security": "Sécurité",
        "privacy.securityDesc": "Nous utilisons un cryptage standard pour protéger vos informations financières.",
        "privacy.contact": "Contact",
        "privacy.contactDesc": "Si vous avez des questions, contactez-nous à MAN Insan Cendekia Siak.",
    },
    de: {
        "settings.title": "Einstellungen",
        "settings.subtitle": "Verwalten Sie Ihre Einstellungen",
        "settings.account": "Mein Konto",
        "settings.appearance": "Erscheinungsbild",
        "settings.preferences": "Präferenzen",
        "settings.about": "Über",
        "settings.logout": "Abmelden",
        "settings.logoutSuccess": "Erfolgreich abgemeldet",
        "settings.logoutError": "Abmeldung fehlgeschlagen",
        "settings.darkMode": "Dunkelmodus",
        "settings.darkModeActive": "Dunkelmodus aktiv",
        "settings.lightModeActive": "Heller Modus aktiv",
        "settings.themeColor": "Themenfarbe",
        "settings.language": "Sprache",
        "settings.notifications": "Benachrichtigungen",
        "settings.currency": "Währung",
        "settings.privacyPolicy": "Datenschutzrichtlinie",
        "settings.aboutApp": "Über Fiscal",
        "common.soon": "Bald",
        "nav.chat": "KI-Chat",
        "nav.settings": "Einstellungen",
        "dashboard.welcome": "Hallo! 👋",
        "dashboard.welcomeSubtitle": "bereit zu helfen",
        "dashboard.intro": "Geben Sie Transaktionen wie \"Kaffee 5€\" ein oder laden Sie einen Beleg hoch. Ich kann auch Ihre Finanzfragen beantworten!",
        "dashboard.suggestion.expense": "💸 Mittagessen 15€",
        "dashboard.suggestion.income": "💰 Monatsgehalt 3000€",
        "dashboard.suggestion.analytics": "📊 Wochenausgaben?",
        "dashboard.suggestion.tips": "💡 Spartipps",
        "balance.total": "Gesamtsaldo",
        "balance.income": "Einnahmen",
        "balance.expense": "Ausgaben",
        "balance.auto": "Auto",
        "common.processing": "Verarbeitung...",
        "common.cancel": "Abbrechen",
        "common.save": "Speichern",
        "common.delete": "Löschen",
        "common.edit": "Bearbeiten",
        "common.today": "Heute",
        "wallet.title": "Brieftasche",
        "wallet.export": "Exportieren",
        "wallet.exportCsv": "CSV Exportieren",
        "wallet.exportPdf": "PDF Exportieren",
        "wallet.trend": "Trend der letzten 6 Monate",
        "wallet.categoryBreakdown": "Ausgaben nach Kategorie",
        "wallet.insight": "Monatlicher Einblick",
        "wallet.recentTransactions": "Letzte Transaktionen",
        "wallet.noTransactions": "Noch keine Transaktionen",
        "reports.title": "Berichte",
        "reports.monthly": "Monatsbericht",
        "reports.balanceMonth": "Monatssaldo",
        "reports.trend": "6-Monats-Trend",
        "reports.topExpenses": "Top Ausgaben",
        "insights.title": "Einblicke",
        "insights.financial": "Finanzielle Einblicke",
        "insights.savingsRate": "Sparquote",
        "insights.avgDaily": "Durschn./Tag",
        "insights.trend14": "14-Tage-Ausgabentrend",
        "insights.breakdown": "Kategorie-Aufschlüsselung",
        "insights.tips": "Smarte Tipps",
        "goals.title": "Budgetziele",
        "goals.totalBudget": "Gesamtbudget Monat",
        "goals.overBudget": "⚠️ Budget überschritten!",
        "goals.remaining": "verbleibend",
        "goals.loading": "Laden...",
        "goals.empty": "Noch keine Budgetziele",
        "goals.emptyDesc": "Erstellen Sie ein Budget zur Ausgabenkontrolle",
        "goals.status.over": "Über Budget!",
        "goals.status.near": "Nahe Limit",
        "goals.status.onTrack": "Auf Kurs",
        "goals.add": "Ziel Hinzufügen",
        "goals.selectCategory": "Kategorie wählen",
        "goals.amountPlaceholder": "Budgetbetrag",
        "transaction.add": "Transaktion Hinzufügen",
        "transaction.manual": "Manuell",
        "transaction.receipt": "Beleg Hochladen",
        "transaction.receiptPrompt": "Tippen für Foto",
        "transaction.aiProcessing": "KI Verarbeitet...",
        "transaction.amount": "Betrag",
        "transaction.category": "Kategorie",
        "transaction.date": "Datum",
        "transaction.note": "Notiz (optional)",
        "transaction.notePlaceholder": "Notiz hinzufügen...",
        "transaction.save": "Transaktion Speichern",
        "transaction.saved": "Gespeichert",
        "transaction.cancelled": "Abgebrochen",
        "transaction.confirm": "Bestätigen",
        "alerts.budgetOver": "Budget Überschritten!",
        "alerts.budgetOverDesc": "Ausgaben für {category} übersteigen Budget",
        "alerts.budgetNear": "Nahe Limit",
        "alerts.budgetNearDesc": "{category} ist bei {percent}% des Budgets",
        "alerts.spendingFast": "Schnelle Ausgaben",
        "alerts.spendingFastDesc": "Sie geben schneller aus als der Durchschnitt",
        "alerts.expenseIncomeHigh": "Ausgaben > Einnahmen!",
        "alerts.ratioHigh": "Hohes Verhältnis",
        "alerts.expenseHighDesc": "Die Ausgaben dieses Monats übersteigen die Einnahmen!",
        "alerts.ratioHighDesc": "Sie haben {percent}% der Einnahmen ausgegeben",
        "recurring.title": "Wiederkehrende",
        "recurring.add": "Wiederkehrende Hinzufügen",
        "recurring.type": "Typ",
        "recurring.type.income": "Einkommen",
        "recurring.type.expense": "Ausgabe",
        "recurring.amount": "Betrag",
        "recurring.category": "Kategorie",
        "recurring.description": "Beschreibung (optional)",
        "recurring.frequency": "Frequenz",
        "recurring.frequency.daily": "Täglich",
        "recurring.frequency.weekly": "Wöchentlich",
        "recurring.frequency.monthly": "Monatlich",
        "recurring.frequency.yearly": "Jährlich",
        "recurring.startDate": "Startdatum",
        "recurring.next": "Nächste: {date}",
        "recurring.empty": "Keine wiederkehrenden Transaktionen",
        "recurring.emptyDesc": "Monatliche Rechnungen hinzufügen",
        "recurring.active": "Aktiviert",
        "recurring.inactive": "Deaktiviert",
        "recurring.saved": "Wiederkehrende Transaktion gespeichert",
        "recurring.deleted": "Wiederkehrende Transaktion gelöscht",
        "privacy.intro": "Ihre Privatsphäre ist uns wichtig. Diese Richtlinie erklärt, wie Fiscal Ihre Daten sammelt und schützt.",
        "privacy.dataCollection": "Datensammlung",
        "privacy.dataCollectionDesc": "Wir sammeln Daten, die Sie direkt bereitstellen, wie Transaktionsdetails. Wir verkaufen Ihre persönlichen Daten nicht.",
        "privacy.security": "Sicherheit",
        "privacy.securityDesc": "Wir verwenden branchenübliche Verschlüsselung, um Ihre Finanzdaten zu schützen.",
        "privacy.contact": "Kontakt",
        "privacy.contactDesc": "Bei Fragen wenden Sie sich bitte an MAN Insan Cendekia Siak.",
    },
};

export const currencyConfig: Record<Language, { code: string; locale: string }> = {
    id: { code: 'IDR', locale: 'id-ID' },
    en: { code: 'USD', locale: 'en-US' },
    es: { code: 'EUR', locale: 'es-ES' },
    fr: { code: 'EUR', locale: 'fr-FR' },
    de: { code: 'EUR', locale: 'de-DE' },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem("fiscal_language");
        return (saved as Language) || "id";
    });

    useEffect(() => {
        localStorage.setItem("fiscal_language", language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    const formatCurrency = (amount: number) => {
        const config = currencyConfig[language];

        // Convert if not IDR (assuming base is IDR)
        let convertedAmount = amount;
        if (config.code !== 'IDR') {
            const rate = exchangeRates[config.code];
            if (rate) {
                convertedAmount = amount * rate;
            }
        }

        return new Intl.NumberFormat(config.locale, {
            style: 'currency',
            currency: config.code,
            minimumFractionDigits: config.code === 'IDR' ? 0 : 2,
            maximumFractionDigits: config.code === 'IDR' ? 0 : 2,
        }).format(convertedAmount);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
